### ISSUE TITLE
关于测试报错

### ISSUE THREAD

**Issue by zhouhaonan011** [chenxy99/SD-FSIC#2]
您好
我在测试时，会不断报错
Traceback (most recent call last):
  File "/home/1/SD-FSIC-master/multi_eval_ensemble.py", line 104, in <module>
    loss, split_predictions, lang_stats = eval_utils.eval_split(model, crit, loader,
  File "/home/1/SD-FSIC-master/eval_utils.py", line 240, in eval_split
    lang_stats = language_eval(dataset, predictions, n_predictions, eval_kwargs, split)
  File "/home/1/SD-FSIC-master/eval_utils.py", line 91, in language_eval
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

请问您有什么头绪吗，这个是用0做了除法？

**Comment by chenxy99** [comment]
Sorry that I did not notice this issue for a long time. For the code eval_utlis.py, I directly follow the repository https://github.com/ruotianluo/self-critical.pytorch. You may check the python version 3.6.10 and the related library version from my [sc_rtl.yml](https://github.com/chenxy99/SD-FSIC/blob/master/sc_rtl.yml) file.
