### ISSUE TITLE
can I run your code using transformer model?

### ISSUE THREAD

**Issue by qq123aa456** [chenxy99/SD-FSIC#3]
I have successful run your model using fc_rl.yml，but when i choose transformer model ,it error.
'AttEnsemble' object has no attribute 'done_beams'
or 'ModuleList' object has no attribute 'd_model'
what fix should I do?

**Comment by chenxy99** [comment]
Hello,

Thanks for your interest in our code. However, I did not implement the transformer few-shot image captioning. Since I refer to that baseline [self-critical](https://github.com/ruotianluo/self-critical.pytorch) but forgot to remove the transformer yaml file.

Best
